import img1 from "../assets/Group 10.png";
import img2 from "../assets/Group 11.png";
import img3 from "../assets/Group 12.png";
import dr1 from "../assets/div.med-stl-3-photo-inner (3).png";
import dr2 from "../assets/div.med-stl-3-photo-inner (5).png";
import dr3 from "../assets/div.med-stl-3-photo-inner (4).png";

export const promoImg = [img1, img2, img3, img1, img2, img3];

export const drSpecialist = [
  {
    name: "Dr Ahmad Khan",
    specialist: "Neurologist",
    imgUrl: dr1,
  },
  {
    name: "Dr Heena Sachdeva",
    specialist: "Orthopedic",
    imgUrl: dr2,
  },
  {
    name: "Dr Ankur Sharma",
    specialist: "Medicine",
    imgUrl: dr3,
  },
  {
    name: "Dr Ahmad Khan",
    specialist: "Neurologist",
    imgUrl: dr1,
  },
  {
    name: "Dr Heena Sachdeva",
    specialist: "Orthopedic",
    imgUrl: dr2,
  },
  {
    name: "Dr Ankur Sharma",
    specialist: "Medicine",
    imgUrl: dr3,
  },
];
//'Our Pricing','Our Gallery','Appointment'
export const footerList = [
  "About Us",
  "Orthology",
  "About Us",
  "Our Pricing",
  "Neurology",
  "Our Pricing",
  "Our Gallery",
  "Dental Care",
  "Our Gallery",
  "Appointment",
  "Opthalmology",
  "Appointment",
  "Privacy Policy",
  "Cardiology",
  "Privacy Policy",
];

export const slotAvailable = [
  {
    slotCount: 15,
    date: 0,
    day: "first",
  },
  {
    slotCount: 10,
    date: 1,
    day: "second",
  },
  {
    slotCount: 9,
    date: 2,
    day: "third",
  },
  {
    slotCount: 10,
    date: 3,
    day: "fourth",
  },
  {
    slotCount: 6,
    date: 4,
    day: "fifth",
  },
  {
    slotCount: 10,
    date: 5,
    day: "sixth",
  },
  {
    slotCount: 6,
    date: 6,
    day: "seventh",
  },
];

export const availableSlotTime = [
  {
    first: [
      "Morning",
      "7:30AM",
      "08:00AM",
      "9:00AM",
      "10:30AM",
      "11:00AM",
      "Afternoon",
      "12:30PM",
      "1:00PM",
      "2:00PM",
      "03:30PM",
      "04:00PM",
      "Evening",
      "5:30PM",
      "6:00PM",
      "7:00PM",
      "8:00PM",
      "9:00PM",
    ],
  },
  {
    second: [
      "Morning",
      "7:30AM",
      "",
      "9:00AM",
      "",
      "11:00AM",
      "Afternoon",
      "12:30PM",
      "",
      "2:00PM",
      "",
      "04:00PM",
      "Evening",
      "",
      "6:00PM",
      "7:00PM",
      "8:00PM",
      "9:00PM",
    ],
  },
  {
    third: [
      "Morning",
      "",
      "08:00AM",
      "",
      "10:30AM",
      "",
      "Afternoon",
      "12:30PM",
      "1:00PM",
      "2:00PM",
      "03:30PM",
      "04:00PM",
      "Evening",
      "",
      "6:00PM",
      "7:00PM",
      "",
      "",
    ],
  },
  {
    fourth: [
      "Morning",
      "7:30AM",
      "08:00AM",
      "9:00AM",
      "10:30AM",
      "11:00AM",
      "Afternoon",
      "",
      "",
      "",
      "03:30PM",
      "04:00PM",
      "Evening",
      "5:30PM",
      "6:00PM",
      "7:00PM",
      "",
      "",
    ],
  },
  {
    fifth: [
      "Morning",
      "",
      "",
      "9:00AM",
      "",
      "",
      "Afternoon",
      "12:30PM",
      "1:00PM",
      "",
      "",
      "04:00PM",
      "Evening",
      "",
      "6:00PM",
      "",
      "8:00PM",
      "",
    ],
  },
  {
    sixth: [
      "Morning",
      "",
      "",
      "9:00AM",
      "",
      "11:00AM",
      "Afternoon",
      "12:30PM",
      "1:00PM",
      "2:00PM",
      "03:30PM",
      "04:00PM",
      "Evening",
      "5:30PM",
      "6:00PM",
      "",
      "8:00PM",
      "",
    ],
  },
  {
    seventh: [
      "Morning",
      "7:30AM",
      "08:00AM",
      "",
      "",
      "",
      "Afternoon",
      "",
      "",
      "",
      "",
      "04:00PM",
      "Evening",
      "5:30PM",
      "6:00PM",
      "",
      "",
      "9:00PM",
    ],
  },
];
